name: oxycare_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cupertino_icons: ^1.0.6
  fl_chart: ^1.0.0
  csv: ^6.0.0
  path_provider: ^2.0.15
  permission_handler: ^12.0.1
  pdf: ^3.10.4
  open_file: ^3.3.2
  printing: ^5.12.0
  flutter_blue_plus: ^1.31.13
  intl: ^0.20.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/ufs_logo_nome_lado.png
    - assets/logo_cuidar.png
    - assets/sounds/alert.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21
